# Generated by Django 3.1.4 on 2020-12-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orders_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
    ]
